apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 066014486c26cdb436a6323f54e029939119396f
    app.openshift.io/vcs-uri: https://github.com/chrisley75/nextjs-sample-app
  labels:
    app: nextjs-app-chrisley
    app.kubernetes.io/instance: nextjs-app-chrisley
    app.kubernetes.io/name: nextjs-app-chrisley
  name: nextjs-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nextjs-app-chrisley
    app.kubernetes.io/instance: nextjs-app-chrisley
    app.kubernetes.io/name: nextjs-app-chrisley
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 066014486c26cdb436a6323f54e029939119396f
    app.openshift.io/vcs-uri: https://github.com/chrisley75/nextjs-sample-app
  labels:
    app: nextjs-app-chrisley
    app.kubernetes.io/instance: nextjs-app-chrisley
    app.kubernetes.io/name: nextjs-app-chrisley
  name: nextjs-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nextjs-app-chrisley
      app.kubernetes.io/instance: nextjs-app-chrisley
      app.kubernetes.io/name: nextjs-app-chrisley
  template:
    metadata:
      annotations:
        app.openshift.io/runtime: js
        app.openshift.io/vcs-ref: 066014486c26cdb436a6323f54e029939119396f
        app.openshift.io/vcs-uri: https://github.com/chrisley75/nextjs-sample-app
      labels:
        app: nextjs-app-chrisley
        app.kubernetes.io/instance: nextjs-app-chrisley
        app.kubernetes.io/name: nextjs-app-chrisley
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/chrisley7506/simple-nextjs-app:066014486c26cdb436a6323f54e029939119396f
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nextjs-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 066014486c26cdb436a6323f54e029939119396f
    app.openshift.io/vcs-uri: https://github.com/chrisley75/nextjs-sample-app
  labels:
    app: nextjs-app-chrisley
    app.kubernetes.io/instance: nextjs-app-chrisley
    app.kubernetes.io/name: nextjs-app-chrisley
  name: nextjs-app
spec:
  to:
    kind: Service
    name: nextjs-app
    weight: 100
  wildcardPolicy: None
